### ISSUE TITLE
Zwei Anlagen

### ISSUE THREAD

**Issue by iobroker99** [TA2k/ioBroker.viessmannapi#1]
Hello,
die APi funktioniert sehr gut, aaaaber: ich habe in meinem ViCare Account zwei Anlagen an zwei Standorten. Die Daten der ersten Anlage sind in der API, die der zweiten Anlage aber nicht. Any ideas wie ich da drankomme?

**Comment by TA2k** [comment]
Bitte im ioBroker Forum kontaktieren https://forum.iobroker.net/user/tombox ich bräuchte kurz zugang zu der anlage um zu verstehen was da anders ist. Ob es zwei Installationen oder zwei Gateways sind

**Comment by TA2k** [comment]
fix with 2.0.4
