### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by ArchGithub** [TA2k/ioBroker.viessmannapi#10]
Ich bekomme immer wieder die Fehlermeldung:
viessmannapi.0 | 2022-01-19 11:07:47.864 | error | {"viErrorId":"req-xxxxxxxxxxxxxxxxxxxxxxxx","statusCode":500,"errorType":"INTERNAL_ERROR","message":"Internal  server error"}
-- | -- | -- | --
viessmannapi.0 | 2022-01-19 11:07:47.864 | error | Error: Request failed with status code 500
viessmannapi.0 | 2022-01-19 11:07:47.858 | error | https://api.viessmann.com/iot/v1/equipment/installations/$installation/gateways/$gateway/devices/$id/features

**Comment by TA2k** [comment]
Fehler kommt von viessmann
