### ISSUE TITLE
Warmwasser Standard Datenpunkte fehlen!

### ISSUE THREAD

**Issue by ArchGithub** [TA2k/ioBroker.viessmannapi#11]
Ich finde alle Datenpunkte nur nicht den der Soll-Warmwassertemperatur Standard der 1. bzw. den SetValue Datenpunkt dazu. Die Warmwassertemperatur ist vorhanden.
Bzgl. Warmwassertemperatur 2 "Schnelles Warmwasser" sind die Datenpunkte vorhanden.
Ich hatte auch den Adapter schon neu installiert.

**Comment by TA2k** [comment]
Bitte hier schauen wo er ist
https://developer.viessmann.com/de/doc/iot/data-points

Wenn nicht vorhanden im Viessmann Forum danach fragen
https://www.viessmann-community.com/t5/The-Viessmann-API/bd-p/dev-viessmann-api
