### ISSUE TITLE
Missing data point

### ISSUE THREAD

**Issue by HighStairs** [TA2k/ioBroker.viessmannapi#12]
According to the Viessmann documentation the gas consumption should be accesible and visible. However I'm missing it in iobroker / Objects.

![grafik](https://user-images.githubusercontent.com/85429460/150675166-8cf59182-57ab-47eb-89f5-f6e920f49c06.png)

Thanks for checking!

**Comment by TA2k** [comment]
ioBroker is displaying the raw result of the API. No datepoints are filtered. Please ask viessmann for missing datapoints
https://www.viessmann-community.com/t5/The-Viessmann-API/bd-p/dev-viessmann-api
