### ISSUE TITLE
Fehler im Log: Could not parse value for id viessmannapi.0

### ISSUE THREAD

**Issue by MarkSau** [TA2k/ioBroker.viessmannapi#13]
Hallo
seit dem letzten Update 2.0.8 kommt im Log immer wieder folgende Fehlermeldungen:

`
<html>
<body>

javascript.0 | 2022-01-28 09:17:10.671 | debug | Could not parse value for id viessmannapi.0.30581.events.data31.origin into object: Unexpected token s in JSON at position 0
javascript.0 | 2022-01-28 09:17:10.666 | debug | Could not parse value for id viessmannapi.0.30581.events.data30.origin into object: Unexpected token s in JSON at position 0
javascript.0 | 2022-01-28 09:17:10.665 | debug | Could not parse value for id viessmannapi.0.30581.events.data30.origin into object: Unexpected token s in JSON at position 0
javascript.0 | 2022-01-28 09:17:10.641 | debug | Could not parse value for id viessmannapi.0.30581.events.data29.origin into object: Unexpected token s in JSON at position 0
javascript.0 | 2022-01-28 09:17:10.641 | debug | Could not parse value for id viessmannapi.0.30581.events.data29.origin into object: Unexpected token s in JSON at position 0
javascript.0 | 2022-01-28 09:17:10.622 | debug | Could not parse value for id viessmannapi.0.30581.events.data28.origin into object: Unexpected token s in JSON at position 0

</body>
</html>`

Die Meldungen stören nicht, sind aber unschön, weil eben viele.

**Comment by TA2k** [comment]
Es wäre hilfreich das komplette objekt vor dem parsen zu haben und den log level auf info setzen

**Comment by MarkSau** [comment]
Hi.. Das interessante ist, das ich aktiv gar nichts in dem Bereich parse. In zwei Scripte werden andere Objekte ausserhalb des "Event" Baums geprüft und ggfs. gesetzt. 

Was kann ich machen/liefern um hier Licht ins Dunkle zu bringen? 
Loglevel Info, ok..aber welcher Adapter...

**Comment by TA2k** [comment]
Aber der fehler kommt von javascript.0 und nicht viessmann
