### ISSUE TITLE
Schedule wird nicht richtig dargestellt

### ISSUE THREAD

**Issue by ElRedef** [TA2k/ioBroker.viessmannapi#2]
Hallo,

bei mir werden alle 'Schedules'  nicht korrekt angezeigt. Es fehlen die Wochentage. Es wird sozusagen nur ein Tag angezeigt.
Beispiel:

![schedule](https://user-images.githubusercontent.com/66745270/137631686-e5ec6179-b617-49f7-b6b7-979a89c7cbd3.JPG)
. 

Gelesen wird aber wirklich alles. Hier ein Auszug aus dem Log (kann sein dass die Beispiele nicht die selbe Schedule darstellen):

`,{"properties":{"active":{"value":true,"type":"boolean"},"entries":{"value":{"mon":[{"start":"00:00","end":"24:00","mode":"normal","position":0}],"tue":[{"start":"00:00","end":"24:00","mode":"normal","position":0}],"wed":[{"start":"00:00","end":"24:00","mode":"normal","position":0}],"thu":[{"start":"00:00","end":"24:00","mode":"normal","position":0}],"fri":[{"start":"00:00","end":"24:00","mode":"normal","position":0}],"sat":[{"start":"00:00","end":"24:00","mode":"normal","position":0}],"sun":[{"start":"00:00","end":"24:00","mode":"normal","position":0}]},"type":"Schedule"}},`

Allgemein finde ich es (für meinen Anwendungsfall) ungeschickt dass die Schedule 'ausgepackt' wird.  Im alten Adapter war er ein Objekt als JSON String. 
Ich muss einen der Schedules regelmässig ändern. D.h. ich lese ihn, ändere ihn und schreibe ihn zurück. Wenn er 'ausgepackt' ist muss ich erst den Baum parsen und das ganze wieder zusammen bauen. Ober ist natürlich machbar. 

Gruß
Johannes

**Comment by TA2k** [comment]
Habe das in der github version angepasst bitte überprüfen ob das so passt. Am besten vorher die Objekte manuell löschen

**Comment by ElRedef** [comment]
Danke! Sieht gut aus!
