### ISSUE TITLE
Implementierung Vitocharge VX3

### ISSUE THREAD

**Issue by DrHouse03** [TA2k/ioBroker.viessmannapi#21]
Hallo,
ich bekomme vielleicht demnächst eine PV Anlage mit Speicher.
Wechselrichter wäre ein Viessmann Vitocharge VX3. Ein Kriterium für den Kauf ist, dass er mit ioBroker kommuniziert.
Könnte man diesen bitte hier implementieren?

Danke

**Comment by TA2k** [comment]
Hier nochmal die offizielle Liste
https://documentation.viessmann.com/static/compatibility
Ansonsten kann nur Viessmann weitere Details beantworten

https://www.viessmann-community.com/t5/The-Viessmann-API/bd-p/dev-viessmann-api
