### ISSUE TITLE
AxiosError: Request failed with status code 404

### ISSUE THREAD

**Issue by 0xdefec71f** [TA2k/ioBroker.viessmannapi#28]
Hallo,
seit 2 Tagen bekomme ich keine Werte mehr im Adapter und stattdessen diese Meldungen im Log:

![image](https://user-images.githubusercontent.com/35151132/224926621-91c0a041-12cb-472d-bb03-cd3232b9f6d3.png)

"404 Gateway not found" bedeutet für mich als Laie, dass der Endpunkt nicht erreichbar ist. Alle anderen Adapter haben aber vollen Internetzugriff und auch der Viessmannadapter hat bis vor 2 Tagen wunderbar funktioniert. Was kann es sein?

VG

**Comment by TA2k** [comment]
Alle viessmann geräte und dein viessmann gateway neugestartet?

**Comment by 0xdefec71f** [comment]
Ja, mehrfach. Auch das Gateway habe ich neu gestartet, obwohl die Viessmann App einwandfrei kontakt hat.

**Comment by TA2k** [comment]
kannst du die GitHub version testen ob die funktioniert

**Comment by 0xdefec71f** [comment]
Ich kenne nur die GitHub Version und habe sie vor langer Zeit über die "Katze" und der URL https://github.com/TA2k/ioBroker.viessmannapi installiert. Ich habe nun mit dieser URL noch einmal drüber installiert, aber die Meldungen bleiben gleich.

![image](https://user-images.githubusercontent.com/35151132/224985208-bf709e81-82d2-426f-9813-5d951bbff7d8.png)

**Comment by 0xdefec71f** [comment]
Ich habe nun den Adapter deinstalliert, **_gelöscht_** und neu installiert. Jetzt geht es wieder. Was auch immer...
