### ISSUE TITLE
Keine API Registrierung mehr möglich

### ISSUE THREAD

**Issue by nicomania** [TA2k/ioBroker.viessmannapi#3]
Hallo zusammen,

vielen Dank für den neuen Plugin! Wollte es mit meiner neuen Heizung und iobroker gleich probieren. Nur leider scheint Viessmann keine API Keys mehr herzugeben. Auf [https://developer.viessmann.com/de/clients](https://developer.viessmann.com/de/clients) kann man nur noch lesen: "Leider ist der Login zum Viessmann Developer Portal noch nicht verfügbar." Man kann sich nur benachrichtigen lassen, sobald sich das mal ändert.

Steh ich auf dem Schlauch oder haben die den Hahn zu gedreht? Haben sich wohl in kurzer Zeit zu viele angemeldet? Gibt es noch eine andere Möglichkeit den Key zu bekommen?

VG

**Comment by TA2k** [comment]
Das kann eher das viessmann forum beantworten
https://www.viessmann-community.com/t5/Developer/ct-p/Developer

**Comment by nicomania** [comment]
Da dieser Plugin ohne API Key für neue User unbrauchbar ist, dachte ich, es wäre von substanziellem Interesse. Ich bitte vielmals um Entschuldigung, falls ich den elitären Kreis mit meiner unüberlegten Frage belästigt haben sollte.

**Comment by baaahm** [comment]
Entspann dich. Die Antwort ist absolut richtig, für Viessmannservices sind die auch selbst die richtigen Ansprechpartner. Trotzdem klingt es für mich eher nach Wartungsarbeiten, die waren irgendwann um diesen Zeitraum jetzt angekündigt meine ich mich zu erinnern. Vielleicht später nochmal versuchen.

**Comment by nicomania** [comment]
Ich bin entspannt. Trotzdem ist seine Antwort daneben. Meine Fragen wurden auch nicht beantwortet.
