### ISSUE TITLE
viessmannapi settings not visible

### ISSUE THREAD

**Issue by netchron-personal** [TA2k/ioBroker.viessmannapi#3]
Hi,
I installed the viessmannapi-adapter via the "install via custom URL" since the adapter is not visible in the official adapter list.
I can see a datapoint for it created (viessmannapi/admin), however the viessmannapi is missing in the adapter list.
How can I change the settings?

**Comment by TA2k** [comment]
Create a instance manual 
see https://forum.iobroker.net/topic/46778/test-viessmannapi-v2-0-0?_=1636910006441

**Comment by netchron-personal** [comment]
Vielen 1000 Dank :)
Der Schritt hat gefehlt - danke für die mega schnelle Antwort :)
