### ISSUE TITLE
status code 404

### ISSUE THREAD

**Issue by SentiQ** [TA2k/ioBroker.viessmannapi#30]
After updating to the newest version the adapter is not working anymore:

{"viErrorId":"\|00-9913959b19f9417ea808df1a555ca287-aafd7e869fc641e7-01.c35e265a_","statusCode":404,"errorType":"GATEWAY_NOT_FOUND","message":"Gateway not found","extendedPayload":{}}
AxiosError: Request failed with status code 404
https://api.viessmann.com/iot/v1/features/installations/1253262/gateways/{gatewaySerial}/devices/0/features

**Comment by Rookiestyle** [comment]
Same here, after installing 2.0.9 the error is gone

````
https://api.viessmann.com/iot/v1/features/installations/$installation/gateways/{gatewaySerial}/devices/$id/features
...
let url = element.url.replace("$id", device.id);
url = url.replace("$installation", installation.id);
url = url.replace("$gatewaySerial", device.gatewaySerial);
````

Maybe it's simply changing *{gatewaySerial}* to *$gatewaySerial* in the url?


This is how it looks in my 2.0.9 code
```
https://api.viessmann.com/iot/v1/equipment/installations/$installation/gateways/$gateway/devices/$id/features
...
url = url.replace("$gateway", device.gatewaySerial)
```

**Comment by Rookiestyle** [comment]
I no longer observe this error after I applied my fix.

Still wondering a bit as why there are still v1 urls although you switched to new endpoints?

**Comment by TA2k** [comment]
please try 2.1.1
