### ISSUE TITLE
Invalid IDs

### ISSUE THREAD

**Issue by Rookiestyle** [TA2k/ioBroker.viessmannapi#38]
**Describe the bug**  
When I expand the objects of my viessmannapi instance, I see several errors like this in the log:
```Invalid pattern on subscribe: The pattern "viessmannapi.0.xxxxxxx.gateways01.devices01.roles.type:product;Vitodens_200" is not a valid ID pattern```

Those errors are issued for admin.0 but the IDs are created by viessmannapi.

iobroker.admin versions < 6.10.1 face a restart loop iobroker/iobroker.admin#2105
Starting with iobroker.admin 6.10.1 this is gone, the invalid IDs remain.

Is there something you can do or are those IDs defined by Viessmann and you MUST take them as is?
**Versions:**  
 - Adapter version: 2.1.1
 - JS-Controller version: 5.0.12
 - Node version: 18.17.1
 - Operating system: Raspberry bullseye

**Comment by TA2k** [comment]
please send a debug log via mail
tombox2020@gmail.com

**Comment by Rookiestyle** [comment]
Mail sent

The file contains debug log for viessmannapi and admin.
I replaced personal data (access token, address returned by Viessmann, …) – the rest is unchanged

**Comment by Rookiestyle** [comment]
long pending update to close this issue... Fixed with ioBroker/ioBroker.admin#2105
