### ISSUE TITLE
Each refresh counts as 3 API calls?

### ISSUE THREAD

**Issue by BuZZy1337** [TA2k/ioBroker.viessmannapi#40]
Im running into Error 429 (Request limit exceeded)..

I noticed that each request counts as 3 on the Viessmann API...

For example i open the Viessmann Dashboard and i see that i used 100 requests so far..
When the Adapter pulls the data the counter is increasing to 103.
So it seems like the adapter is making three calls every time the interval is triggered..?

**Comment by TA2k** [comment]
For each device one request you can see this in debug log

**Comment by BuZZy1337** [comment]
I only have one device...

**Comment by TA2k** [comment]
please reinstall again
