### ISSUE TITLE
Failed authentication retry

### ISSUE THREAD

**Issue by mwojtko1** [TA2k/ioBroker.viessmannapi#43]
Hello,
I've got a question regarding authentication retries:
https://github.com/TA2k/ioBroker.viessmannapi/blob/7ac4a92f91aa5df8d3d11e92418dae0ad4085059/main.js#L34C10-L34C10
Why is it retried with POST method instead of GET?

**Comment by TA2k** [comment]
Only submitting commands are in the retry included because sometimes command end to the gateway are failing
This is not related to authentication
