### ISSUE TITLE
Seit Aktivierung von ViCare Einzelraumsteuerung API RATE_LIMIT_EXCEEDED

### ISSUE THREAD

**Issue by ckoeber83** [TA2k/ioBroker.viessmannapi#48]
Hi TA2k

ich habe seit Freitag 01.12.2023 auf ViCare Einzelraumsteuerung Umgestellt.

(_2x ViCare Fußboden-Thermostat ZK03838, 2x ViCare Repeater ZK03839, 1x Heizkörper-Thermostat ZK03840 und 12x ViCare Klimasensoren ZK03839_)

Seit dem erhalte ich im [ioBroker.viessmannapi](https://github.com/TA2k/ioBroker.viessmannapi) Adapter nach 4h Laufzeit:
```
RATE_LIMIT_EXCEEDED
API calls rate limit has been exceeded. Please wait until your limit will renew.
Rate limit reached. Will be reseted next day 02:00
```

Ich habe dazu jetzt im Schreiben des Beitrages [Seit Aktivierung von ViCare Einzelraumsteuerung API RATE_LIMIT_EXCEEDED](https://www.viessmann-community.com/t5/The-Viessmann-API/Seit-Aktivierung-von-ViCare-Einzelraumsteuerung-API-RATE-LIMIT/m-p/393416#M1923) in der Viessmann Community herausgefunden, dass durch die Einzelraumsteuerung jetzt diverse Zigbee Devices angelegt werden, welche über den [ioBroker.viessmannapi](https://github.com/TA2k/ioBroker.viessmannapi/blob/master/README.md) Adapter immer mit Abgefragt werden

Zum einen unter viessmannapi.0.xxxxxxx.gateways01

![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/71625457-9e8c-4898-8aa7-c0251edc52ff)

Und viessmannapi.0.xxxxxxx.zigbee...
![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/33b4ea0e-cd73-45b7-8750-32d7e1b71aac)

Und Räume bringt auch nochmal eine ganze Latte an Objekten
viessmannapi.0.xxxxxx.RoomControl-1.features.rooms

![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/a05990e8-d027-49dc-b00b-2412bcc3c0f6)

Halt je nachdem was man so alles gekauft und angelegt hat. 😁

Meine viessmannapi Instanz hat mittlerweile **4465 Objekte** (Täglich steigend durch Error Logs = _viessmannapi.0.xxxxxx.0.features.device.messages.errors.raw.properties.entries_)

Nun haben diese Datenpunkte aber in der [Free Basic API Version ](https://developer.viessmann.com/start/pricing.html)
keinen Relevanten Inhalt und ich benötige diese auch so nicht im ioBroker.

Kann man beispielsweise die Tiefe oder Baumstruktur bei der Abfrage eingrenzen, dass nicht immer alle Objekte in den API Calls angefragen werden, was ja ganz schnell das Abfragelimit seitens Viessmann erreicht 😔

Aktuell Frage ich beispielsweise nur Wert unter
```
viessmannapi.0.xxxxxx.0.features.heating
viessmannapi.0.xxxxxx.0.features.ventilation
```
ab.

Den Rest brauche ich erstmal nicht.
Der ganze ViCare kram steht ja schon im Obergeordneten Objektbaum _viessmannapi.0.xxxxxx_

![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/9c37a6ee-c65f-4a48-9aa7-9b9ca64a98c0)

Eine Filterfunktion wäre hier also hilfreich und wünschenswert!

Oder was macht diese "Index of Which Gateway shall be use" Funktion, welche ich heute erst durch ein Update erhalten habe.
![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/cef057e3-fd4c-4c53-9e57-0c2ac361314c)

Vielen Dank und beste Grüße ✌

**Comment by TA2k** [comment]
Wie würde so ein filter aussehen?
`0, HeatDemandControl`

**Comment by ckoeber83** [comment]
Nach der Installations ID xxxxxx die Instanz 0, dann > features > heating / ventilation
> viessmannapi.0.xxxxxx.0.features.heating
> viessmannapi.0.xxxxxx.0.features.ventilation

![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/19b787b1-600a-4c81-ac41-bddfcdb0456f)

**Comment by TA2k** [comment]
die GitHub version hat jetzt eine allowlist bitte mal mit debug log testen ob das funktioniert

**Comment by ckoeber83** [comment]
Seit dem in das ViCare Smart Climatic in 09/2023 aktiviert habe, habe ich einen extremen Anstieg an API transactions gehabt:

![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/e88415f3-72b4-4263-99ab-705092b20708)

Und nun komme ich immer über das 1450 API calls per day Limit 👎

**Comment by ckoeber83** [comment]
> die GitHub version hat jetzt eine allowlist bitte mal mit debug log testen ob das funktioniert

Hi TA2k,

es sieht so aus im [debug.txt](https://github.com/TA2k/ioBroker.viessmannapi/files/13604389/debug.txt), als ob er jetzt ein **ignore for update:  gateway, RoomControl-1 & zigbee...** macht.
Ich hatte die zwar alle gelöscht aus dem Objektbaum und diese kommen beim Adapterneustart wieder.
Ob er die jetzt immer neu pollt, weiß ich noch nicht...

Kann man _address_, _events_ & _gateways01_ auch noch ignorieren? Gerade unter events sind 2349 Objekte!

Laut Adapterdefinition müsste ich doch nur den Ordner "0" einschließen und alles andere Ignorieren oder?

![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/d916f868-7861-490c-9e9c-b7fcd40d854c)
![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/872996de-ad6d-4ea5-9612-e1e7bade05c3)

VG ✌

**Comment by TA2k** [comment]
Also erstellt werden immer alle sonst weiß man ja nicht welche man erlauben möchte es ist ja hier nur das Update wichtig
Im debug log solltest du auch die updates sehen

**Comment by ckoeber83** [comment]
Hi [TA2k](https://github.com/TA2k),
ich beobachte das mal.
Aktuell sieht es sehr gut aus mit aktueller Einstellung.
Damit habe ich aktuell eine API transaction aller 5 Minuten poll Intervall, was am Ende 288 API transactions / pro Tag bedeuten würde.

![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/d916f868-7861-490c-9e9c-b7fcd40d854c)

Ich lasse das erstmal so morgen und über's Wochenende laufen und berichte wieder. (Bin über's WE verreist.)

Ich danke erstmal vielmals für die schnelle Hilfe und wahrscheinlich praktikable Lösung. 👍
Schönes Wochenende!

**Comment by ckoeber83** [comment]
Hi,

es scheint in der Tat jetzt wieder gut zu laufen mit der Allowlist = "0"
Habe sogar das Update device status in minutes auf "1" Minute gestellt und erhalte 2339 API transactions gestern:
![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/3354389f-d2e8-4fbc-8b9c-e6233af49937)

Und keine Aussetzer in der Aufzeichnung am Tagesende, obwohl dies eigentlich die "_[1450 API calls per day](https://developer.viessmann.com/start/pricing.html)_" überschreitet 👍
![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/fc384d42-523f-42bd-8079-a18ec7dfd3d8)

Danke [TA2k](https://github.com/TA2k) und viele Grüße ✌

**Comment by ckoeber83** [comment]
Hi,

es scheint in der Tat jetzt wieder gut zu laufen mit der Allowlist = "0"
Habe sogar das Update device status in minutes auf "1" Minute gestellt und erhalte 2339 API transactions gestern:
![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/3354389f-d2e8-4fbc-8b9c-e6233af49937)

Und keine Aussetzer in der Aufzeichnung am Tagesende, obwohl dies eigentlich die "_[1450 API calls per day](https://developer.viessmann.com/start/pricing.html)_" überschreitet 👍
![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/fc384d42-523f-42bd-8079-a18ec7dfd3d8)

Danke [TA2k](https://github.com/TA2k) und viele Grüße ✌

**Comment by ckoeber83** [comment]
Hi @TA2k ,

mir ist jetzt noch aufgefallen, das er immer die ID "**roomControl**" ignoriert, obwohl ich diese in die AllowList geschrieben habe:

Somit ignoriert er leider jetzt bei mir die Temperaturen der einzelnen Räume, welche ich aktuell aufzeichnen will, da ich jetzt die [Advanced API](https://checkout.viessmann.com/items?app=developer-portal&product=7968306&billing=monthly&appUrl=https:%2F%2Fapp.developer.viessmann.com) habe.

![grafik](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/31f12a33-24d9-4d74-b888-bc9a8b4307ea)
![grafik](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/e2767f92-12e4-4dab-9acc-55231ea8868b)

Danke und viele Grüße

**Comment by TA2k** [comment]
roomcontrol wird ignoriert weil role gateway oder virtual ist kann das sein?

**Comment by ckoeber83** [comment]
@TA2k ,

unter https://api.viessmann.com/iot/v1/equipment/installations?includeGateways=true
wird mir angezeigt `"deviceType": "roomControl"` und als Rolle `"type:virtual;smartRoomControl"`

![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/f99d0762-3979-4cc3-890d-6d51ca4dd10d)

Eingetlich müsst er doch, durch das erlauben der "RoomControl-1" alle Unterpdafe mit Updaten 🤔
Denke das zumindest so verstanden zu haben.

![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/7cca8d38-7132-4694-94db-95c4de6fd086)

**Comment by TA2k** [comment]
im moment sind virtual und gateway vom update ausgenommen sie werden nur bei adapter start angelegt

**Comment by ckoeber83** [comment]
@TA2k ich habe jetzt "`0, RoomControl-1, roomControl, virtual;smartRoomControl,`" in der Allow Liste und trotzdem kommt noch im Debug Log `"debug ignore roomControl"` 🤔

**Comment by TA2k** [comment]
Eigentlich haben virtual devices keine Funktion und werden fix ignoriert.
In der GitHub Version gibt es eine Option um virtuelle devices zu aktivieren

**Comment by ckoeber83** [comment]
@TA2k ich glaube das sieht gut aus mit v2.4.0. 👍

Ich erlaube jetzt meine Instanz "0" (Heizung selber), die Raumkontrolle (RoomControl-1) und zwei ViCare Fußbodenthermostateinheiten ZK03838 (zigbee-142d41fffe797475, zigbee-142d41fffe7cf7e9) + Virtual Devices (Checkbox).

`0, RoomControl-1, zigbee-142d41fffe797475, zigbee-142d41fffe7cf7e9`

Das Update Intervall habe ich auf "2" Minuten gestellt und er macht jetzt pro 2 Minuten = 4 [API transactions](https://app.developer.viessmann.com/transactions) = 2880 [API transactions](https://app.developer.viessmann.com/transactions) / Tag und damit noch unter dem Rate Limit von 3000 👍 (In der [Advanced API](https://checkout.viessmann.com/items?app=developer-portal&product=7968306&billing=monthly&appUrl=https:%2F%2Fapp.developer.viessmann.com))
(Ob das passt, sehe ich in 24h 🤞)


![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/c56cea7c-2db7-4d27-9346-b342adff9489)

Vielen Dank nochmal für deine schnelle Hilfe und super Support 👍

**Comment by TA2k** [comment]
welche information bekommst du aus dem RoomControl-1

**Comment by ckoeber83** [comment]
@TA2k 
da hole ich mir die Temperatur und Luftfeuchte der Räume her: ([Baumstruktur als json](https://github.com/TA2k/ioBroker.viessmannapi/files/13708833/viessmannapi.0.RoomControl-1.json))

![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/870259b6-ef57-487c-8a3b-1999b5a83f5e)
![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/6de5c922-b4b3-421c-abea-523d42e37c06)

Auch den [ViCare CO₂-Sensor](https://www.viessmann.de/de/produkte/steuerung-und-konnektivitaet/vicare-co2-sensor.html) und Fenster offen Erkennung kann man da auslesen:

![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/c188e006-f11a-4cda-93f5-840a2ea2d81c)

Zudem kann man noch die gesetzten Temperaturen der einzelnen Räume auslesen und die manuellen / programierten Temperatur setzen und sehen, wenn eine Heizanforderung in den Räumen besteht.

Die [Advanced API](https://checkout.viessmann.com/items?app=developer-portal&product=7968306&billing=yearly&appUrl=https:%2F%2Fapp.developer.viessmann.com) stellt ja dafür entsprechend [Datenpunkte](https://documentation.viessmann.com/static/iot/data-points) bereit:
Für [ViCare Fußbodenthermostat](https://www.viessmann.de/de/produkte/steuerung-und-konnektivitaet/vicare-app/komponenten.html#Fu%C3%9Fbodenheizung)
![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/4b231064-34e4-4269-9e5b-f78492137c99)
Für [ViCare Klimasensor](https://www.viessmann.de/de/produkte/steuerung-und-konnektivitaet/vicare-app/komponenten.html#Temperatur)
![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/efb511bb-c31e-422e-9852-1fae2a2e956f)
Für [ViCare Heizkörperthermostat](https://www.viessmann.de/de/produkte/steuerung-und-konnektivitaet/vicare-app/komponenten.html#App)
![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/169459b4-f0b2-4a10-80de-b2ec34d3c7f6)


Leider kostet der Spaß aber auch **12€ /Monat** bei einer Jahreslaufzeit 😔 _(Annual subscription save up to 40%)_
[Preise](https://developer.viessmann.com/start/pricing.html)
![image](https://github.com/TA2k/ioBroker.viessmannapi/assets/52466072/a286f874-bff6-4e0a-9ac8-3c60c00d1dbd)
