### ISSUE TITLE
 hello, i have a problem with the interval setting for viessmannapi (restriction to 1450). i get every day after 3 to 6 hours the message that the count is exceeded. what parameters should be set to avoid this problem. regards 

### ISSUE THREAD

**Issue by hbe8125** [TA2k/ioBroker.viessmannapi#6]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by TA2k** [comment]
Increase the minute interval in the adapter settings

**Comment by hbe8125** [comment]
Hello,

tried values 60, 600,1024, 6000 and 12000, but still the sam result se attachments, looks like the intervall is not working the adapter start every minute.
![iob-Screenshot 2021-12-20 115340](https://user-images.githubusercontent.com/96343227/146757042-1170509e-8786-4911-bef4-81035cb9508a.jpg)
![iob-Screenshot 2021-12-20 115430](https://user-images.githubusercontent.com/96343227/146757043-1d2904cb-4b39-49e2-8ce7-78c9df26c2d0.jpg)


plea help me out, thanks

**Comment by TA2k** [comment]
With this error you have to wait 24h until you can set a new interval
