### ISSUE TITLE
Bekomme Adapter nicht installiert

### ISSUE THREAD

**Issue by Schmattek** [TA2k/ioBroker.viessmannapi#7]
Ich bekomme beim installieren über die Konsole immer folgende Fehler:

root@iobroker:~# npm i iobroker.viessmannapi
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ iobroker.viessmannapi@2.0.6
updated 1 package and audited 619 packages in 4.595s

15 packages are looking for funding
  run `npm fund` for details

found 9 vulnerabilities (6 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details

Wie bekomme ich das gelöst?

**Comment by TA2k** [comment]
Wie inder Anleitung im Forum unter Instanz eine Instanz erzeugen
