### ISSUE TITLE
Error: Request failed with status code 500

### ISSUE THREAD

**Issue by holofury** [TA2k/ioBroker.viessmannapi#8]
Hallo,

ich bekomme regelmäßig folgende Fehler:

viessmannapi.0 | 2022-01-07 19:45:52.807 | error | Error: Request failed with status code 500
viessmannapi.0 | 2022-01-07 19:45:52.789 | error | https://api.viessmann.com/iot/v1/equipment/installations/$installation/gateways/$gateway/devices/$id/features

Zugang bei Viessmann ist korrekt eingerichtet, Client ID auch schon erneuert.

**Comment by TA2k** [comment]
Viessmann server sind noch nicht stabil kann ignoriert werden
