### ISSUE TITLE
Google reCAPTCHA deaktivieren funktioniert nicht

### ISSUE THREAD

**Issue by ghost** [TA2k/ioBroker.viessmannapi#9]
Hallo,
ich bekomme den Adapter nicht ans laufen. 
Habe eine Client ID erstellt und im Adapter noch Benutzername und Kennwort eingegeben.

Beim nächsten Punkt "**deactivate Google reCAPTCHA**" komme ich leider nicht weiter.
Wenn ich die URI: **http://localhost:4200/** eingebe, kommt "**Diese Webseite ist nicht erreichbar**".

Was mache ich falsch? Wo ist der Denkfehler?

Bin für jede Hilfe sehr dankbar.

Beste Grüße 

Michael

**Comment by TA2k** [comment]
Ich weiß nicht was du meinst wenn du schon eine client id hast wo gibst du denn dann bitte die url nochmal ein bzw die url is doch schon ausgefüllt.

Bitte nicht die url in den browser eingeben. client id und benutzer passwort reicht

<img width="353" alt="image" src="https://user-images.githubusercontent.com/1307684/149398489-f3f7e0a2-b785-4b4e-b035-3489c4bba364.png">

**Comment by ghost** [comment]
Hallo @TA2k ,
Danke, das war es. Jetzt klappt es. 
Sorry, habe ich irgendwie übersehen.

Vielen Dank für die schnelle Antwort.

Beste Grüße 

Micha
